
name: Deploy App

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Doppler
        uses: DopplerHQ/cli-action
        with:
          token: ${{ secrets.DOPPLER_TOKEN }}
          command: run -- node app.js

