name: AutomaticHost
on:
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v4
      with:
        node-version: '16.x'
    - run: |
        npm ci
        npm install build
        doppler secrets download --no-file --format env --no-prompt --config dev
    - run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout --orphan gh-pages
        git reset
        git add main/* -f
        git mv main/* ./ -k
        git commit -m "Update hosted version"
    - uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        branch: gh-pages
